name: Deploy Tetris Web App
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup SwiftWasm
      uses: swiftwasm/setup-swiftwasm@v1
      with:
        swift-version: 'wasm-5.9.2-RELEASE'

    # ▼▼▼ 以前の2ステップを、この1ステップに置き換える ▼▼▼
    - name: Build with Carton
      run: swift run carton bundle
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Bundle
